/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CursValutarRouteImport } from './routes/curs-valutar'
import { Route as IndexRouteImport } from './routes/index'

const CursValutarRoute = CursValutarRouteImport.update({
  id: '/curs-valutar',
  path: '/curs-valutar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/curs-valutar': typeof CursValutarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/curs-valutar': typeof CursValutarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/curs-valutar': typeof CursValutarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/curs-valutar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/curs-valutar'
  id: '__root__' | '/' | '/curs-valutar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CursValutarRoute: typeof CursValutarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/curs-valutar': {
      id: '/curs-valutar'
      path: '/curs-valutar'
      fullPath: '/curs-valutar'
      preLoaderRoute: typeof CursValutarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CursValutarRoute: CursValutarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
